"""add teams_x_divisions and teams_x_brackets

Revision ID: 3fb87b7c4ffd
Revises: b26004a5450d
Create Date: 2026-03-01 19:47:19.288636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb87b7c4ffd'
down_revision: Union[str, None] = 'b26004a5450d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_x_divisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.Column('bias', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'division_id', name='unique_team_division')
    )
    op.create_index(op.f('ix_teams_x_divisions_division_id'), 'teams_x_divisions', ['division_id'], unique=False)
    op.create_index(op.f('ix_teams_x_divisions_id'), 'teams_x_divisions', ['id'], unique=False)
    op.create_table('teams_x_brackets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('bracket_id', sa.BigInteger(), nullable=False),
    sa.Column('bracket_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_x_brackets_bracket_id'), 'teams_x_brackets', ['bracket_id'], unique=False)
    op.create_index(op.f('ix_teams_x_brackets_id'), 'teams_x_brackets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_x_brackets_id'), table_name='teams_x_brackets')
    op.drop_index(op.f('ix_teams_x_brackets_bracket_id'), table_name='teams_x_brackets')
    op.drop_table('teams_x_brackets')
    op.drop_index(op.f('ix_teams_x_divisions_id'), table_name='teams_x_divisions')
    op.drop_index(op.f('ix_teams_x_divisions_division_id'), table_name='teams_x_divisions')
    op.drop_table('teams_x_divisions')
    # ### end Alembic commands ###
