"""Clean players schema update

Revision ID: 4d104f40d6d3
Revises: b527f9006c57
Create Date: 2025-04-21 17:15:57.285829

"""
from typing import Sequence, Union
from sqlalchemy import table, column, String

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d104f40d6d3'
down_revision: Union[str, None] = 'b527f9006c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('players', sa.Column('rank', sa.String(), nullable=True))

    # 2. Backfill existing rows
    players = table('players', column('rank', String))
    op.execute(players.update().values({'rank': 'Unranked'}))

    # 3. Alter column to NOT NULL
    op.alter_column('players', 'rank', nullable=False)
    op.add_column('players', sa.Column('division', sa.String(), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('lunch', sa.String(), nullable=True))
    op.add_column('players', sa.Column('paid', sa.Boolean(), server_default='t', nullable=False))
    op.add_column('players', sa.Column('bogu', sa.Boolean(), server_default='t', nullable=True))
    op.create_index(op.f('ix_players_age'), 'players', ['age'], unique=False)
    op.create_index(op.f('ix_players_bogu'), 'players', ['bogu'], unique=False)
    op.create_index(op.f('ix_players_division'), 'players', ['division'], unique=False)
    op.create_index(op.f('ix_players_lunch'), 'players', ['lunch'], unique=False)
    op.create_index(op.f('ix_players_paid'), 'players', ['paid'], unique=False)
    op.create_index(op.f('ix_players_rank'), 'players', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_rank'), table_name='players')
    op.drop_index(op.f('ix_players_paid'), table_name='players')
    op.drop_index(op.f('ix_players_lunch'), table_name='players')
    op.drop_index(op.f('ix_players_division'), table_name='players')
    op.drop_index(op.f('ix_players_bogu'), table_name='players')
    op.drop_index(op.f('ix_players_age'), table_name='players')
    op.drop_column('players', 'bogu')
    op.drop_column('players', 'paid')
    op.drop_column('players', 'lunch')
    op.drop_column('players', 'age')
    op.drop_column('players', 'division')
    op.drop_column('players', 'rank')
    # ### end Alembic commands ###
