"""add more fields to tournaments schema

Revision ID: 64ce80e74e22
Revises: 41f7234fea4b
Create Date: 2026-03-04 22:05:57.164294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ce80e74e22'
down_revision: Union[str, None] = '41f7234fea4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
