"""create tables mapping divisions and brackets to players

Revision ID: 75cf90b754e0
Revises: b6ee732dee9c
Create Date: 2025-08-30 14:17:44.376345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cf90b754e0'
down_revision: Union[str, None] = 'b6ee732dee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('margin_mins', sa.Integer(), nullable=False),
    sa.Column('division_type', sa.Enum('INDIVIDUALS', 'TEAMS', name='division_type'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=False)
    op.create_index(op.f('ix_divisions_prefix'), 'divisions', ['prefix'], unique=False)
    op.create_index(op.f('ix_divisions_tournament_id'), 'divisions', ['tournament_id'], unique=False)
    op.create_table('brackets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.Column('num_players', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brackets_division_id'), 'brackets', ['division_id'], unique=False)
    op.create_index(op.f('ix_brackets_id'), 'brackets', ['id'], unique=False)
    op.create_index(op.f('ix_brackets_index'), 'brackets', ['index'], unique=False)
    op.create_table('players_x_divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_x_divisions_division_id'), 'players_x_divisions', ['division_id'], unique=False)
    op.create_index(op.f('ix_players_x_divisions_id'), 'players_x_divisions', ['id'], unique=False)
    op.create_table('players_x_brackets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('bracket_id', sa.BigInteger(), nullable=False),
    sa.Column('bracket_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_x_brackets_bracket_id'), 'players_x_brackets', ['bracket_id'], unique=False)
    op.create_index(op.f('ix_players_x_brackets_id'), 'players_x_brackets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_x_brackets_id'), table_name='players_x_brackets')
    op.drop_index(op.f('ix_players_x_brackets_bracket_id'), table_name='players_x_brackets')
    op.drop_table('players_x_brackets')
    op.drop_index(op.f('ix_players_x_divisions_id'), table_name='players_x_divisions')
    op.drop_index(op.f('ix_players_x_divisions_division_id'), table_name='players_x_divisions')
    op.drop_table('players_x_divisions')
    op.drop_index(op.f('ix_brackets_index'), table_name='brackets')
    op.drop_index(op.f('ix_brackets_id'), table_name='brackets')
    op.drop_index(op.f('ix_brackets_division_id'), table_name='brackets')
    op.drop_table('brackets')
    op.drop_index(op.f('ix_divisions_tournament_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_prefix'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
