"""create new players_field schema

Revision ID: 87996d026884
Revises: a0978d780fd9
Create Date: 2025-06-22 21:53:06.130529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87996d026884'
down_revision: Union[str, None] = 'a0978d780fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('include', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('type', sa.Enum('text', 'boolean', 'number', 'dropdown', name='player_field_type'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_field_id'), 'players_field', ['id'], unique=False)
    op.create_index(op.f('ix_players_field_tournament_id'), 'players_field', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_field_tournament_id'), table_name='players_field')
    op.drop_index(op.f('ix_players_field_id'), table_name='players_field')
    op.drop_table('players_field')
    # ### end Alembic commands ###
