"""remove users_x_clubs relation

Revision ID: 9b2593241df4
Revises: eea2ab655796
Create Date: 2025-06-25 22:40:31.900184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b2593241df4'
down_revision: Union[str, None] = 'eea2ab655796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('representative', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_abbreviation'), 'clubs', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_clubs_contact_email'), 'clubs', ['contact_email'], unique=False)
    op.create_index(op.f('ix_clubs_creator_id'), 'clubs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_representative'), 'clubs', ['representative'], unique=False)
    op.drop_column('teams', 'logo_path')
    op.drop_column('teams', 'swiss_score')
    op.drop_column('teams', 'elo_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('elo_score', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('swiss_score', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('logo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clubs_representative'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_creator_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_contact_email'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_abbreviation'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
