"""remove active field from players table

Revision ID: a0978d780fd9
Revises: d6b59d60553b
Create Date: 2025-06-22 17:14:13.049275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0978d780fd9'
down_revision: Union[str, None] = 'd6b59d60553b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_active', table_name='players')
    op.drop_column('players', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index('ix_players_active', 'players', ['active'], unique=False)
    # ### end Alembic commands ###
