"""add back divisions type column

Revision ID: b26004a5450d
Revises: d24b3bdbf897
Create Date: 2025-09-13 17:40:03.078303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26004a5450d'
down_revision: Union[str, None] = 'd24b3bdbf897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisions', sa.Column('division_type', sa.Enum('INDIVIDUALS', 'TEAMS', name='division_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('divisions', 'division_type')
    # ### end Alembic commands ###
