"""update players and clubs table

Revision ID: cac21e157c5c
Revises: 4d104f40d6d3
Create Date: 2025-05-22 21:39:59.323295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cac21e157c5c'
down_revision: Union[str, None] = '4d104f40d6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   # 1) Add as nullable
    op.add_column(
        'clubs',
        sa.Column('abbreviation', sa.String(), nullable=True),
    )
    # 2) Back-fill existing rows (here with an empty string)
    op.execute(
        "UPDATE clubs SET abbreviation = '' WHERE abbreviation IS NULL"
    )
    # 3) Now enforce NOT NULL
    op.alter_column(
        'clubs',
        'abbreviation',
        nullable=False,
    )
    op.add_column('clubs', sa.Column('tournament_id', sa.BigInteger(), nullable=False))
    op.add_column('clubs', sa.Column('team_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_clubs_abbreviation'), 'clubs', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_clubs_tournament_id'), 'clubs', ['tournament_id'], unique=False)
    op.create_foreign_key(None, 'clubs', 'tournaments', ['tournament_id'], ['id'])
    op.add_column('players', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index('ix_players_age', table_name='players')
    op.drop_index('ix_players_bogu', table_name='players')
    op.drop_index('ix_players_division', table_name='players')
    op.drop_index('ix_players_lunch', table_name='players')
    op.drop_index('ix_players_name', table_name='players')
    op.drop_index('ix_players_paid', table_name='players')
    op.drop_index('ix_players_rank', table_name='players')
    op.create_index('ix_players_data_gin', 'players', ['data'], unique=False, postgresql_using='gin')
    op.drop_column('players', 'division')
    op.drop_column('players', 'rank')
    op.drop_column('players', 'lunch')
    op.drop_column('players', 'age')
    op.drop_column('players', 'name')
    op.drop_column('players', 'paid')
    op.drop_column('players', 'bogu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('bogu', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('paid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('lunch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('rank', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_players_data_gin', table_name='players', postgresql_using='gin')
    op.create_index('ix_players_rank', 'players', ['rank'], unique=False)
    op.create_index('ix_players_paid', 'players', ['paid'], unique=False)
    op.create_index('ix_players_name', 'players', ['name'], unique=False)
    op.create_index('ix_players_lunch', 'players', ['lunch'], unique=False)
    op.create_index('ix_players_division', 'players', ['division'], unique=False)
    op.create_index('ix_players_bogu', 'players', ['bogu'], unique=False)
    op.create_index('ix_players_age', 'players', ['age'], unique=False)
    op.drop_column('players', 'data')
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_index(op.f('ix_clubs_tournament_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_abbreviation'), table_name='clubs')
    op.drop_column('clubs', 'team_count')
    op.drop_column('clubs', 'tournament_id')
    op.drop_column('clubs', 'abbreviation')
    # ### end Alembic commands ###
