"""update tournaments table to remove match duration and add bias field to players_x_divisions table

Revision ID: d24b3bdbf897
Revises: 75cf90b754e0
Create Date: 2025-09-13 16:59:52.548045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24b3bdbf897'
down_revision: Union[str, None] = '75cf90b754e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('margin_mins', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=False)
    op.create_index(op.f('ix_divisions_prefix'), 'divisions', ['prefix'], unique=False)
    op.create_index(op.f('ix_divisions_tournament_id'), 'divisions', ['tournament_id'], unique=False)
    op.create_table('players_x_divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.Column('bias', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'division_id', name='unique_player_division')
    )
    op.create_index(op.f('ix_players_x_divisions_division_id'), 'players_x_divisions', ['division_id'], unique=False)
    op.create_index(op.f('ix_players_x_divisions_id'), 'players_x_divisions', ['id'], unique=False)
    op.drop_index('ix_brackets_index', table_name='brackets')
    op.create_foreign_key(None, 'brackets', 'divisions', ['division_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brackets', type_='foreignkey')
    op.create_index('ix_brackets_index', 'brackets', ['index'], unique=False)
    op.drop_index(op.f('ix_players_x_divisions_id'), table_name='players_x_divisions')
    op.drop_index(op.f('ix_players_x_divisions_division_id'), table_name='players_x_divisions')
    op.drop_table('players_x_divisions')
    op.drop_index(op.f('ix_divisions_tournament_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_prefix'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
