"""update teams tables and add new table for teams category

Revision ID: f9077e4dd036
Revises: 66e0415df80d
Create Date: 2025-07-17 22:51:51.303621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9077e4dd036'
down_revision: Union[str, None] = '66e0415df80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_category_id'), 'teams_category', ['id'], unique=False)
    op.create_index(op.f('ix_teams_category_tournament_id'), 'teams_category', ['tournament_id'], unique=False)
    op.add_column('players', sa.Column('name', sa.String(), nullable=False))
    op.add_column('players', sa.Column('club', sa.String(), nullable=False))
    op.add_column('players', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_club'), 'players', ['club'], unique=False)
    op.create_index(op.f('ix_players_code'), 'players', ['code'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.drop_constraint('players_tournament_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_column('players', 'draws')
    op.drop_column('players', 'swiss_score')
    op.drop_column('players', 'elo_score')
    op.drop_column('players', 'losses')
    op.add_column('players_x_teams', sa.Column('position', sa.Enum('SENPO', 'JIHOU', 'CHUKEN', 'FUKUSHOU', 'TAISHO', name='player_position_type'), nullable=True))
    op.add_column('teams', sa.Column('code', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('category', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_teams_category'), 'teams', ['category'], unique=False)
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.drop_constraint('teams_tournament_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teams', 'draws')
    op.drop_column('teams', 'losses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('losses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('draws', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_tournament_id_fkey', 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_category'), table_name='teams')
    op.drop_column('teams', 'updated')
    op.drop_column('teams', 'category')
    op.drop_column('teams', 'code')
    op.drop_column('players_x_teams', 'position')
    op.add_column('players', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('elo_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('swiss_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('draws', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_tournament_id_fkey', 'players', 'tournaments', ['tournament_id'], ['id'])
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_code'), table_name='players')
    op.drop_index(op.f('ix_players_club'), table_name='players')
    op.drop_column('players', 'code')
    op.drop_column('players', 'club')
    op.drop_column('players', 'name')
    op.drop_index(op.f('ix_teams_category_tournament_id'), table_name='teams_category')
    op.drop_index(op.f('ix_teams_category_id'), table_name='teams_category')
    op.drop_table('teams_category')
    # ### end Alembic commands ###
